apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
  namespace: cloudops-kubernetes
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS users (
      id SERIAL PRIMARY KEY,
      name TEXT NOT NULL,
      email TEXT UNIQUE NOT NULL
    );

    CREATE ROLE web_anon NOLOGIN;

    GRANT USAGE ON SCHEMA public TO web_anon;
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE users TO web_anon;
    GRANT USAGE, SELECT ON SEQUENCE users_id_seq TO web_anon;